<?php

function getValue($name, $def)
{ $ret = $def;
  if( isset($_GET[$name]) ){
    $ret = $_GET[$name];
  }
  if( isset($_POST[$name]) ){
    $ret = $_POST[$name];
  }
  return $ret;
}

$style = getValue("style", "");
$user = getValue("user", "");
$pass = getValue("pass", "");
$host = getValue("host", "");
$speech = getValue("speech", "0");
$game = getValue("game", "");

?>
<script type='text/javascript' >
<?php 
include("editor.js");
include("client.js");
include("webrtc.js");
?>
</script>


<!DOCTYPE html>
<html>
<head>
<TITLE>PRISM Client 2025</TITLE>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body onload="onPageLoaded();">

<div style='display:none;' >
  // args from PHP
  <?php if( $user != ""){ ?>
  <input id='defuser' value='<?php echo "$user"; ?>' />
  <?php }if( $pass != ""){ ?>
  <input id='defpass' value='<?php echo "$pass"; ?>' />
  <?php }if( $style != ""){ ?>
  <input id='defstyle' value='<?php echo "$style"; ?>' />
  <?php }if( $host != ""){ ?>
  <input id='defhost' value='<?php echo "$host"; ?>' />
   <?php }if( $speech != ""){ ?>
  <input id='defspeech' value='<?php echo "$speech"; ?>' />
   <?php }if( $game != ""){ ?>
  <input id='defsgame' value='<?php echo "$game"; ?>' />
  <?php } ?>
</div>

<div id='welcome' >
  <p>The client connects to a secure web socket port on the server<br />
  which is using a self signed certificate. To accept the connection use this<br />
  <a href="https://moddersandrockers.com:4202" > LINK </a>. Once you have <br />
  done this you can refresh this page and you will see the Welcome page instead.
</p>
<p>If the Welcome page is not shown after a few seconds then the PRISM server<br />
 may not be running.
</p>
</div>
<div id="outer" style='max-width:1000px;min-width:800px;' >
<table>
  <tr>
    <td valign='top'>
      <div id='welcome-info' >
        <p>
        Welcome to the Web interface to <a href="history.htm">PRISM</a>. 
        PRISM is a Multi User Dungeon that started off as a TinyMud 
        <a href="https://en.wikipedia.org/wiki/TinyMUD">(Wikipedia)</a>.
        The current PRISM database initially was user generated by players
        when it was being run at Imperial College up to 1994. The database was 
        expanded by adding the maps from the "C" port of <a href='https://en.wikipedia.org/wiki/Colossal_Cave_Adventure'>Adventure</a> 
        and ths "C" port of <a href='https://en.wikipedia.org/wiki/Zork' >Dungeon</a>.
        The database moved to the USA and was available on and off. Today 
        the game engine runs on a private Linux server with a public frontend 
        that provides the Telnet and Web interfaces.
        </p>
        <input type='button' onclick='UIshowHide(0, "welcome-info");' value='Hide' />
        <input type='button' onclick='UIspeechIOS();' value='Speech for iOS' />

      </div>
    <div id='webprompt'  style="display:none;">
      <p>Click to login as guest and start or enter info below. </p>
      <image src='resources/adventure.png'  onclick='UIwebaction(2);' style='cursor:pointer;'/>
      <image src='resources/dungeon.png'  onclick='UIwebaction(3);'  style='cursor:pointer;'/>
      <image src='resources/shades.png'   onclick='UIwebaction(4);'  style='cursor:pointer;'/>
      <table>
        <tr><th>User</th><td><input type='text' id='webuser' size='5' /></td></tr>
        <tr><th>Pass</th><td><input type='password' id='webpass' size='5' /></td></tr>
        <tr><th><input type='button' value='Connect' onclick='UIwebaction(0);' /></th>
        <th><input type='button' value='Create'  onclick='UIwebaction(1);' /></th></tr>
      </table>
    </div>
      <div id="chat1" style="display:none; border-style:solid; border-color:red;" >
        <div id="chat1_status" style="font-family: 'courier new', monospace; display:none; background-color: green; ">
        </div>
        <div id="chat1_chatLog" style="font-family: 'courier new', monospace; max-width:1000px; min-width:800px; ">
        </div>
      </div>
        <div id="chat1_chatInput"  style="display:none;" >
          <table><tr><td>Cmd: </td><td><input id="chat1_chatText" type="text" size=20 /></td></tr></table>
        </div>
    </td>
    <td valign='top'>
      <div id='compass'  style="display:none;">
        <p>Common commands include</p>
        <table>
          <tr><td><image src="resources/nw.png"  onclick='UIsendCmd("nw", 0, 1, -1);' style='cursor:pointer;'/></td>
          <td><image src="resources/north.png"   onclick='UIsendCmd("n", 0, 1, -1);' style='cursor:pointer;'/></td>
          <td><image src="resources/ne.png"   onclick='UIsendCmd("ne", 0, 1, -1);' style='cursor:pointer;'/></td></tr>
          <tr><td><image src="resources/west.png"   onclick='UIsendCmd("w", 0, 1, -1);' style='cursor:pointer;'/></td>
          <td><image src="resources/look.png"   onclick='UIsendCmd("look", 0, 1, -1);' style='cursor:pointer;'/></td>
          <td><image src="resources/east.png"   onclick='UIsendCmd("e", 0, 1, -1);' style='cursor:pointer;'/></td></tr>
          <tr><td><image src="resources/sw.png"   onclick='UIsendCmd("sw", 0, 1, -1);' style='cursor:pointer;'/></td>
          <td><image src="resources/south.png"   onclick='UIsendCmd("s", 0, 1, -1);' style='cursor:pointer;'/></td>
          <td><image src="resources/se.png"   onclick='UIsendCmd("se", 0, 1, -1);' style='cursor:pointer;'/></td></tr>
          <tr><td><image src="resources/in.png"   onclick='UIsendCmd("in", 0, 1, -1);' style='cursor:pointer;'/></td>
          <td><image src="resources/out.png"   onclick='UIsendCmd("out", 0, 1, -1);' style='cursor:pointer;'/></td><td></td></tr>
        </table>
      </div>
    </td>
    <td valign='top'>
      <div id="xchat2" style="display:none;" >
        <div id="chat2_status" style="font-family: 'courier new', monospace; display:none;">
        </div>
        <div id="chat2_chatLog" style="font-family: 'courier new', monospace;">
        </div>
      </div>
        <div id="chat2_chatInput"  style="display:none;" >
          <table><tr><td>>Cmd: <input id="chat2_chatText" type="text" size=20 /></td></tr></table>
        </div>
    </td>
    <td valign='top' >
      <div id='media' style="display:none;">
        <input type='button' value='Start Video' id='video-button' onclick='UIstartVideo();' />
      </div>
      <div id='webrtc' style='display:none;' >
        <div id="display-area" style="position:relative;" >
          <img src="resources/chat2.png" style="position:absolute; z-index:0;"/>
          <video id="local-video" autoplay playsinline muted style="position:absolute; z-index:2;"></video>
          <span id='local-user' style="position:absolute; z-index:3;" >User</span>
          <span id='local-location' style="position:absolute; z-index:3;" >Location</span>
          <video id='rem-1-video' autoplay playsinline style="position:absolute; z-index:4;"></video>
          <span id='rem-1-user' style="position:absolute; z-index:6;" >User</span>
          <span id='rem-1-location' style="position:absolute; z-index:6;" >Location</span>
          <video id='rem-2-video' autoplay playsinline style="position:absolute; z-index:4;"></video>
          <span id='rem-2-user' style="position:absolute; z-index:6;" >User</span>
          <span id='rem-2-location' style="position:absolute; z-index:6;" >Location</span>
          <video id='rem-3-video' autoplay playsinline style="position:absolute; z-index:4;"></video>
          <span id='rem-3-user' style="position:absolute; z-index:6;" >User</span>
          <span id='rem-3-location' style="position:absolute; z-index:6;" >Location</span>
          <span id='rem-1-bg' style="position:absolute; z-index:3; back-ground: blue;"></span>
        </div>
        <div style="position:relative; top: 310px;">
          <input type="button" id="startrtc" onclick="UIstartStopRTC();" value="Start Video Chat"   ></input>
          <div id='remoteUsers' >
            <p>Remote user list shown here</p>
          </div>
        </div>
      </div>

    </td>
    <td valign='top'>
      <div id="editor" style="display:none;border-style:solid; border-color:green;" >
        <table>
          <tr><th >Object</th><td><span id='dbref'></span></td><th>Flags</th><td><span id='flags'></span></td></tr>
          <tr><th >Name</th><td><span id='name'></span></td></tr>
          <tr><th ><span id='lock'>Description</span></th><td><span id='description'></span></td></tr>
          <tr><th >Owner</th><td><span id='owner'></span></td></tr>
          <tr><th >class</th><td><span id='class'></span></td></tr>
          <tr><th >zone</th><td><span id='zone'></span></td></tr>
          <tr><th >Contents</th><td><div id='contents'></div></td></tr>
          <tr><th >Commands</th><td><div id='commands'></div></td></tr>
        </table>
      </div>
    </td>
  </tr>
</table>
</div>
</body>
</html>
